fsb.smartcontract-main/fsb.smartcontract/fsb.smartcontract/Controllers/CompanyController.cs
using fsb.smartcontract.Services.Company;
using fsb.smartcontract.Services.Role;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Model.Company;
using Model.Requests;
using Model.Response;
using NToastNotify;
using System.Net.Http;

namespace fsb.smartcontract.Controllers
{
    public class CompanyController : BaseController
    {
        private readonly ILogger<CompanyController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ICompanyService _companyService;

        public CompanyController(
            ILogger<CompanyController> logger,
            IHttpClientFactory factory,
            IToastNotification toastNotification,
            IHttpContextAccessor httpContextAccessor,
            ICompanyService companyService
            ) : base(factory)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _httpContextAccessor = httpContextAccessor;
            _companyService = companyService;
        }

        [Route("danh-sach-cong-ty")]
        public IActionResult Companies()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetListCompany(string searchValue)
        {
            SearchCompanyModel searchModel = talbeSearchModel.Get<SearchCompanyModel>();
            searchModel.SearchValue = searchValue;
            var data = _companyService.GetListCompany(searchModel);
            if (data.Code != StatusCodes.Status200OK)
                _toastNotification.AddErrorToastMessage(data.Message);
            return Json(data);
        }

        [Route("them-moi-cong-ty")]
        public IActionResult CreateCompany()
        {
            return View();
        }

        [HttpPost]
        public IActionResult InsertCompany(CompanyModel model)
        {
            var res = _companyService.CreateCompany(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [HttpPost]
        public IActionResult DeleteCompany(int Id)
        {
            var model = new CompanyModel();
            model.Id = Id;
            var res = _companyService.DeleteCompany(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [Route("sua-cong-ty/{id}")]
        public IActionResult EditCompany(int Id)
        {
            var model = new CompanyModel();
            model.Id = Id;
            var res = _companyService.GetCompanyById(model);

            if (res == null)
                res = new Response<CompanyModel>();
            if (res.Data == null)
                res.Data = new CompanyModel();

            return View(res.Data);
        }

        [HttpPost]
        public IActionResult UpdateCompany(CompanyModel model)
        {
            var res = _companyService.UpdateCompany(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }
    }
}

fsb.smartcontract-main/fsb.smartcontract/fsb.smartcontract/Views/Company/Companies.cshtml
@{
    ViewData["Title"] = "Companies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/app.css" rel="stylesheet" />
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Danh sách công ty</h1>
        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-12">
                <a href="@Url.Action("CreateCompany", "Company")" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Thêm mới</span>
                </a>
            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="form-group row" style="justify-content: flex-end">
                    <div class="col-md-12 col-lg-3 pr-0">
                        <input id="searchValue" class="form-control searchValue" type="text" placeholder="Tìm kiếm" />
                    </div>
                    <a class="btn btn-success btn-icon-split" onclick="reloadWithPageOne()">
                        <span class="icon text-white-50">
                            <i class="fas fa-search"></i>
                        </span>
                    </a>
                </div>
                <table class="table table-bordered" id="monthPlanningTbl" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th data-orderable="false">Mã công ty</th>
                            <th data-orderable="false">Tên công ty</th>
                            <th data-orderable="false">Thao tác</th>
                        </tr>
                    </thead>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Bạn muốn xóa bản ghi này không?</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                <a class="btn btn-danger" onclick="DeleteCompany()">Xóa</a>
            </div>
        </div>
    </div>
</div>
<script>
    var table = undefined;
    $(document).ready(function () {
        loadTable();
        $('#searchValue').keypress(function (e) {
            if (e.which == 13) {
                reloadWithPageOne();
            }
        });
    });
    function reloadWithPageOne() {
        if (table != undefined && table.api().ajax != undefined)
            table.api().ajax.reload(null, true);
    }
    function reload() {
        if (table != undefined && table.api().ajax != undefined)
            table.api().ajax.reload(null,false);
    }
    function loadTable() {
        table = $('#monthPlanningTbl').dataTable({
            "oLanguage": {
                "sEmptyTable": "Không có công ty"
            },
            "language": {
                "paginate": {
                    "previous": "Trước",
                    "next": "Tiếp theo"
                }
            },
            searching: false,
            paging: true,
            lengthChange: false,
            ordering: true,
            filter: false,
            destroy: true,
            orderMulti: false,
            serverSide: true,
            processing: true,
            lengthChange: false,
            "bSort": false,
            ajax: function (data, callback, settings) {
                data.searchValue = $('#searchValue').val();
                postTable("@Url.Action("GetListCompany", "Company")", data, callback);
            },
            "columns": [
                { "data": "companyCode", "name": "CompanyCode", "class": "companyCode" },
                { "data": "companyName", "name": "CompanyName", "class": "companyName" },
                {
                    "class": "action",
                    "render": function (data, row, full) {
                        return "<a class='fas fa-fw fa-edit' title='Sửa' onclick=UpdateCompany('" + full.id + "'); ></a> <a href='#' class='fas fa-fw fa-trash' style='color:red' title='Xóa' data-toggle='modal' data-target='#deleteModal' onclick=openConfirmDelete('" + full.id + "');></a>";
                    }
                }
            ]
        });
    }

    function openConfirmDelete(id) {
        deleteId = id;
    }

    function DeleteCompany() {
        var formData = new FormData();
        formData.append("Id", deleteId);
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("DeleteCompany")', formData, function (data) {
            $('#deleteModal').modal("hide");
            reload();
        });
    }

    function UpdateCompany(id) {
        location.href = '/sua-cong-ty' + "/" + id;
    }
</script>

fsb.smartcontract-main/fsb.smartcontract/fsb.smartcontract/Views/Company/CreateCompany.cshtml
@model Model.Company.CompanyModel
@{
    ViewData["Title"] = "CreateCompany";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Thêm mới nhóm quyền</h1>

        <div class="form-group"></div>
        <form id="CreatePlace" action="#" method="post">
            <div class="col-lg-12 col-xl-8">
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Mã công ty<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="CompanyCode" class="form-control" type="text" placeholder="Nhập mã công ty" />
                        <span asp-validation-for="CompanyCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tên công ty<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="CompanyName" class="form-control" type="text" placeholder="Nhập tên công ty" />
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>

        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-6">
                <a href="@Url.Action("Companies", "Company")" class="btn btn-secondary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Quay lại</span>
                </a>
                <a class="btn btn-success btn-icon-split" onclick="SaveRole()">
                    <span class="icon text-white-50">
                        <i class="fas fa-check"></i>
                    </span>
                    <span class="text">Tạo mới</span>
                </a>
            </div>
        </div>
    </div>
</div>
<script>
    function SaveRole() {
        var lstIdStr = 'CompanyCode,CompanyName';
        if (!RequireValidate(lstIdStr)) {
            toastr.error('Bạn chưa nhập đủ thông tin.');
            return;
        };

        var formData = new FormData();
        formData.append("CompanyCode", $("#CompanyCode").val());
        formData.append("CompanyName", $("#CompanyName").val());
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("InsertCompany")', formData, function (data) {
            if (data.code == "200") {
                setTimeout(
                    function () {
                        location.href = '/danh-sach-cong-ty';
                    }, 1000);
            }
        });
    }
</script>

fsb.smartcontract-main/fsb.smartcontract/fsb.smartcontract/Views/Company/EditCompany.cshtml
@model Model.Company.CompanyModel
@{
    ViewData["Title"] = "EditRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Cập nhật Công ty</h1>

        <div class="form-group"></div>
        <form id="CreateRole" action="#" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="col-lg-12 col-xl-8">
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Mã công ty<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="CompanyCode" class="form-control" type="text" placeholder="Mã công ty" />
                        <span asp-validation-for="CompanyCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tên công ty<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="CompanyName" class="form-control" type="text" placeholder="Tên công ty" />
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>

        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-6">
                <a href="@Url.Action("Companies", "Company")" class="btn btn-secondary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Quay lại</span>
                </a>
                <a class="btn btn-success btn-icon-split" onclick="UpdateCompany()">
                    <span class="icon text-white-50">
                        <i class="fas fa-check"></i>
                    </span>
                    <span class="text">Cập nhật</span>
                </a>
            </div>
        </div>
    </div>
</div>
<script>
    function UpdateCompany() {
        var lstIdStr = 'CompanyCode,CompanyName';
        if (!RequireValidate(lstIdStr)) {
            toastr.error('Bạn chưa nhập đủ thông tin.');
            return;
        };

        var formData = new FormData();
        formData.append("Id", $("#Id").val());
        formData.append("CompanyCode", $("#CompanyCode").val());
        formData.append("CompanyName", $("#CompanyName").val());
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("UpdateCompany")', formData, function (data) {
            if (data.code == "200") {
                setTimeout(
                    function () {
                        location.href = '/danh-sach-cong-ty';
                    }, 1000);
            }
        });
    }
</script>