fsb.smartcontract-main/fsb.smartcontract/fsb.smartcontract/Controllers/RoleController.cs
using fsb.smartcontract.Services.Role;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Model.Requests;
using Model.Response;
using Model.Role;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace fsb.smartcontract.Controllers
{
    public class RoleController : BaseController
    {
        private readonly ILogger<RoleController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IRoleService _roleService;

        public RoleController(
            ILogger<RoleController> logger,
            IHttpClientFactory factory,
            IToastNotification toastNotification,
            IHttpContextAccessor httpContextAccessor,
            IRoleService roleService
            ) : base(factory)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _httpContextAccessor = httpContextAccessor;
            _roleService = roleService;
        }

        [Route("danh-sach-nhom-quyen")]
        public IActionResult Roles()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetListRole(string searchValue)
        {
            SearchRoleModel searchModel = talbeSearchModel.Get<SearchRoleModel>();
            searchModel.SearchValue = searchValue;
            var data = _roleService.GetListRole(searchModel);
            if (data.Code != StatusCodes.Status200OK)
                _toastNotification.AddErrorToastMessage(data.Message);
            return Json(data);
        }

        [Route("them-moi-nhom-quyen")]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public IActionResult InsertRole(RoleModel model)
        {
            var res = _roleService.CreateRole(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [HttpPost]
        public IActionResult DeleteRole(Guid Id)
        {
            var model = new RoleModel();
            model.Id = Id;
            model.UpdateBy = _SessionUser.Id;
            var res = _roleService.DeleteRole(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }

        [Route("sua-nhom-quyen/{id}")]
        public IActionResult EditRole(Guid Id)
        {
            var model = new RoleModel();
            model.Id = Id;
            var res = _roleService.GetRoleById(model);

            if (res == null)
                res = new Response<RoleModel>();
            if (res.Data == null)
                res.Data = new RoleModel();

            return View(res.Data);
        }

        [HttpPost]
        public IActionResult UpdateRole(RoleModel model)
        {
            var res = _roleService.UpdateRole(model);
            if (res.Code == StatusCodes.Status200OK)
            {
                _toastNotification.AddSuccessToastMessage(res.Message);
            }
            else
            {
                _toastNotification.AddErrorToastMessage(res.Message);
            }
            return Json(res);
        }
    }
}

fsb.smartcontract-main/fsb.smartcontract/fsb.smartcontract/Views/Role/CreateRole.cshtml
@model Model.Role.RoleModel
@{
    ViewData["Title"] = "CreateRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Thêm mới nhóm quyền</h1>

        <div class="form-group"></div>
        <form id="CreatePlace" action="#" method="post">
            <div class="col-lg-12 col-xl-8">
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tên nhóm quyền<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="RoleName" class="form-control" type="text" placeholder="Nhập nhóm quyền" />
                        <span asp-validation-for="RoleName" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>

        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-6">
                <a href="@Url.Action("Roles", "Role")" class="btn btn-secondary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Quay lại</span>
                </a>
                <a class="btn btn-success btn-icon-split" onclick="SaveRole()">
                    <span class="icon text-white-50">
                        <i class="fas fa-check"></i>
                    </span>
                    <span class="text">Tạo mới</span>
                </a>
            </div>
        </div>
    </div>
</div>

<script>
    function SaveRole() {
        var lstIdStr = 'RoleName';
        if (!RequireValidate(lstIdStr)) {
            toastr.error('Bạn chưa nhập đủ thông tin.');
            return;
        };

        var formData = new FormData();
        formData.append("RoleName", $("#RoleName").val());
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("InsertRole")', formData, function (data) {
            if (data.code == "200") {
                setTimeout(
                    function () {
                        location.href = '/danh-sach-nhom-quyen';
                    }, 1000);
            }
        });
    }
</script>

fsb.smartcontract-main/fsb.smartcontract/fsb.smartcontract/Views/Role/EditRole.cshtml
@model Model.Role.RoleModel
@{
    ViewData["Title"] = "EditRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Cập nhật nhóm quyền</h1>

        <div class="form-group"></div>
        <form id="CreateRole" action="#" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="col-lg-12 col-xl-8">
                <div class="form-group row">
                    <label class="col-md-12 col-lg-4 label-control">Tên nhóm quyền<span class="text-danger">*</span></label>
                    <div class="col-md-12 col-lg-8">
                        <input asp-for="RoleName" class="form-control" type="text" placeholder="Nhập nhóm quyền" />
                        <span asp-validation-for="RoleName" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>

        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-6">
                <a href="@Url.Action("Roles", "Role")" class="btn btn-secondary btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span class="text">Quay lại</span>
                </a>
                <a class="btn btn-success btn-icon-split" onclick="UpdateRole()">
                    <span class="icon text-white-50">
                        <i class="fas fa-check"></i>
                    </span>
                    <span class="text">Cập nhật</span>
                </a>
            </div>
        </div>
    </div>
</div>

<script>
    function UpdateRole() {
        var lstIdStr = 'RoleName';
        if (!RequireValidate(lstIdStr)) {
            toastr.error('Bạn chưa nhập đủ thông tin.');
            return;
        };

        var formData = new FormData();
        formData.append("Id", $("#Id").val());
        formData.append("RoleName", $("#RoleName").val());
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("UpdateRole")', formData, function (data) {
            if (data.code == "200") {
                setTimeout(
                    function () {
                        location.href = '/danh-sach-nhom-quyen';
                    }, 1000);
            }
        });
    }
</script>

fsb.smartcontract-main/fsb.smartcontract/fsb.smartcontract/Views/Role/Roles.cshtml
@{
    ViewData["Title"] = "Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/app.css" rel="stylesheet" />
<div id="content">
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Danh sách nhóm quyền</h1>
        <div class="h3 mb-2 row">
            <div class="col-md-12 col-lg-12">
                <a href="@Url.Action("CreateRole", "Role")" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Thêm mới</span>
                </a>
            </div>
        </div>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="form-group row" style="justify-content: flex-end">
                    <div class="col-md-12 col-lg-3 pr-0">
                        <input id="searchValue" class="form-control searchValue" type="text" placeholder="Tìm kiếm" />
                    </div>
                    <a class="btn btn-success btn-icon-split" onclick="reloadWithPageOne()">
                        <span class="icon text-white-50">
                            <i class="fas fa-search"></i>
                        </span>
                    </a>
                </div>
                <table class="table table-bordered" id="monthPlanningTbl" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th data-orderable="false">Tên nhóm quyền</th>
                            <th data-orderable="false">Thao tác</th>
                        </tr>
                    </thead>
                    <tfoot>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Bạn muốn xóa bản ghi này không?</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Hủy</button>
                <a class="btn btn-danger" onclick="DeleteRole()">Xóa</a>
            </div>
        </div>
    </div>
</div>
<script>
    var table = undefined;
    $(document).ready(function () {
        loadTable();
        $('#searchValue').keypress(function (e) {
            if (e.which == 13) {
                reloadWithPageOne();
            }
        });
    });
    function reloadWithPageOne() {
        if (table != undefined && table.api().ajax != undefined)
            table.api().ajax.reload(null, true);
    }
    function reload() {
        if (table != undefined && table.api().ajax != undefined)
            table.api().ajax.reload(null,false);
    }
    function loadTable() {
        table = $('#monthPlanningTbl').dataTable({
            "oLanguage": {
                "sEmptyTable": "Không có nhóm quyền"
            },
            "language": {
                "paginate": {
                    "previous": "Trước",
                    "next": "Tiếp theo"
                }
            },
            searching: false,
            paging: true,
            lengthChange: false,
            ordering: true,
            filter: false,
            destroy: true,
            orderMulti: false,
            serverSide: true,
            processing: true,
            lengthChange: false,
            "bSort": false,
            ajax: function (data, callback, settings) {
                data.searchValue = $('#searchValue').val();
                postTable("@Url.Action("GetListRole", "Role")", data, callback);
            },
            "columns": [
                { "data": "roleName", "name": "RoleName", "class": "roleName" },
                {
                    "class": "action",
                    "render": function (data, row, full) {
                        return "<a class='fas fa-fw fa-edit' title='Sửa' onclick=UpdateRole('" + full.id + "'); ></a> <a href='#' class='fas fa-fw fa-trash' style='color:red' title='Xóa' data-toggle='modal' data-target='#deleteModal' onclick=openConfirmDelete('" + full.id + "');></a>";
                    }
                }
            ]
        });
    }

    function openConfirmDelete(id) {
        deleteId = id;
    }

    function DeleteRole() {
        var formData = new FormData();
        formData.append("Id", deleteId);
        formData.append("__RequestVerificationToken", _token);
        postAjax('@Url.Action("DeleteRole")', formData, function (data) {
            $('#deleteModal').modal("hide");
            reload();
        });
    }

    function UpdateRole(id) {
        location.href = '/sua-nhom-quyen' + "/" + id;
    }
</script>